### ISSUE TITLE
 "Your query returned no results" error once the AMI ID is not listed within AWS marketplace.

### ISSUE THREAD

**Issue by evg-mlechko** [cloudposse/terraform-aws-ec2-instance#143]
The AWS instance configured via module, the 'ami' and 'ami_owner' parameters were configured, the instance was created successfully. Once the AMI-ID is removed from the AWS latest amis list (approx in 4 months), there is an error:

`│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.myInstance.data.aws_ami.info,
│   on .terraform/modules/myInstance/main.tf line 71, in data "aws_ami" "info":
│   71: data "aws_ami" "info" {`

It's needed to mention, that actual values for the 'AMI' and 'ami_owner' were saved and haven't changed.
the module version "0.44.0"

**Comment by shomodj** [comment]
Have the same problem, opened an issue with AWS, when I search for the ami its not there, but when I start new box with that ami it shows later in the ami search, terraform is still not working.
But this used to work for me before on 0.44.0

**Comment by shomodj** [comment]
@evg-mlechko does this work before you start a new box
```
aws ec2 describe-images --region ${region_name} --image-ids ${ami_id}
```

**Comment by evg-mlechko** [comment]
hello @shomodj
the `describe-images` command returns `{ "Images": [] }` output. But if we are talking about the case with using this module, it should use the initially predefined (used at the moment of the creation of the EC2 instance) values for `'ami'` and `'ami_owner'` fields. 
So, it was the reason why I created a bug here.
Could you please clarify, what did you mean by saying `start new box`
thanks

**Comment by cdobbyn** [comment]
This is an issue with the module it is better described in this issue:
https://github.com/cloudposse/terraform-aws-ec2-instance/issues/150
