### ISSUE TITLE
Unable to create an instance without any IAM role

### ISSUE THREAD

**Issue by tchwpkgorg** [cloudposse/terraform-aws-ec2-instance#180]
### Describe the Bug

When using terraform aws_instance or AWS web GUI, it is possible to launch an instance which doesn't have any IAM role attached.
It seems to me that it's not possible to launch an instance without any IAM role when using cloudposse/ec2-instance/aws.

### Expected Behavior

IAM role for an instance should not be created when not wanted nor needed.

### Steps to Reproduce

It should be possible to set "instance_profile" to a value which does not create and attach an IAM role.

**Comment by irl** [comment]
Given that #182 was merged and claimed to fix this issue, perhaps this issue should be closed?
