### ISSUE TITLE
couldn't create instance with Public IP and without EIP

### ISSUE THREAD

**Issue by it-svit** [cloudposse/terraform-aws-ec2-instance#23]
This condition doesn't allow to create instance with option `associate_public_ip_address = "true"` and not to create EIP simultaneously
https://github.com/cloudposse/terraform-aws-ec2-instance/blob/6a4eb649edf55240c394aa84ee09ca551ff3ca0c/main.tf#L120

**Comment by osterman** [comment]
Yes, this should always compare against `== "true"`

**Comment by aknysh** [comment]
this was addressed in https://github.com/cloudposse/terraform-aws-ec2-instance/releases/tag/0.7.0
