### ISSUE TITLE
Specify instance count

### ISSUE THREAD

**Issue by prandelicious** [cloudposse/terraform-aws-ec2-instance#27]
How do I specify if I want more than 1 instance of this module?

**Comment by osterman** [comment]
@prandelicious, thanks for reaching out!

Unfortunately, this module does not support a custom `instance_count` parameter via a `variable` at this time. I would welcome the addition if you want to submit a PR. The effort should be minimal. 

https://github.com/cloudposse/terraform-aws-ec2-instance/blob/master/main.tf#L2

**Comment by Jamie-BitFlight** [comment]
@prandelicious soooon you can https://github.com/cloudposse/terraform-aws-ec2-instance/pull/28

**Comment by Jamie-BitFlight** [comment]
@prandelicious although, wouldn't you want to use an asg at that point?

**Comment by osterman** [comment]
@Jamie-BitFlight I think it depends on the use-case. An ASG would be less suitable for stateful applications. 

For example, using the `count` parameter is kind of like `StatefulSets` in kubernetes, while using ASG is more like using `Deployments` in kubenretes. I would use the strategy in this module for deploying Kafka.

**Comment by Jamie-BitFlight** [comment]
@prandelicious A new module has been created, and will be published soon that allows for a set of instances to be created as you require.
https://github.com/cloudposse/terraform-aws-ec2-instance-group/pull/1

**Comment by osterman** [comment]
The instance group module has been released. Big thanks to @jamie-bitflight for seeing it through.
