### ISSUE TITLE
Output for Public IP is empty

### ISSUE THREAD

**Issue by MartinCanovas** [cloudposse/terraform-aws-ec2-instance#67]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Output for Public IP returns empty list.

## Expected Behavior
Output for Public IP returns a public IP address.

## Steps to Reproduce
module "instance" {
  source                        = "git::https://github.com/clouddrove/terraform-aws-ec2.git?ref=tags/0.12.6"
  key_name                      = var.ssh_key_pair
  instance_type                 = var.ec2
  instance_count                = 1
  tenancy                       = "default"
  ami                           = var.ami
  disk_size                     = 10
  ebs_optimized                 = false
  ebs_volume_type               = "gp2"
  assign_eip_address            = false
  associate_public_ip_address   = true
  vpc_security_group_ids_list   = [aws_security_group.sg_instance.id]
  subnet_ids                    = [lookup(module.public_subnets.az_subnet_ids, var.az1)]
  application                   = "app"
  managedby                     = "terraform"
  name                          = "app"
  environment                   = var.stage
  label_order                   = ["environment", "name"]
  instance_tags                 = var.instance_tags
}

output "instance_public_ip" {
  value = module.instance.public_ip
}

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: MacOS 10.15.6
 - terraform providers --version
Terraform v0.12.26
+ provider.aws v2.70.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2

**Comment by aknysh** [comment]
@MartinCanovas 
looks like your example uses the module https://github.com/clouddrove/terraform-aws-ec2, which is not this repo.
Will close for now

**Comment by MartinCanovas** [comment]
@aknysh 
My apologies! I believe I made that mistake because I do use Cloud Posse scripts in other places and Cloud Drove is close enough as far as name goes.
