### ISSUE TITLE
Edge case when providing `instance_profile` that does not yet exist

### ISSUE THREAD

**Issue by ericluria** [cloudposse/terraform-aws-ec2-instance#72]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
When creating an instance profile and passing it into this module, [this data lookup](https://github.com/cloudposse/terraform-aws-ec2-instance/blob/adb9d975e6f02bc48af9a82eca128a3b38175cba/main.tf#L73-L76) fails because the instance profile has not yet been created. The following error occurs when running `terraform plan` on the provided example code below.

I think a possible solution is to accept an `instance_profile_arn` instead of the name of the instance profile, since it's a generated value.

```
Error: Error getting instance profiles: NoSuchEntity: Instance Profile test cannot be found.
	status code: 404, request id: fcf2a09c-bfb3-4041-babd-95133304cf34

  on .terraform/modules/ec2_bug/main.tf line 73, in data "aws_iam_instance_profile" "given":
  73: data "aws_iam_instance_profile" "given" {
```

## Expected Behavior
I expect Terraform to wait for the instance profile to be created before attempting to look it up, so I can create an instance profile and pass it into the EC2 module at the same time.

For context, I'm doing this in order to grant the EC2 instance permissions to reach out to S3 as part of the `user_data` script. I considered adding a policy to the default instance profile created by the module, but at that point it's too late since the user data will have already executed.

## Steps to Reproduce
Here is an example to reproduce the error. Run `terraform plan` on this code, assuming a default VPC exists:
```
variable "aws_assume_role_arn" {}

provider "aws" {
  version = "~> 2.46"

  assume_role {
    role_arn = var.aws_assume_role_arn
  }
}

data "aws_caller_identity" "current" {}

resource "aws_iam_role" "test" {
  assume_role_policy = ""
}
resource "aws_iam_instance_profile" "test" {
  name = "test"
  role = aws_iam_role.test.name
}

data "aws_vpc" "default" {
  default = true
}

resource "aws_subnet" "default" {
  vpc_id     = data.aws_vpc.default.id
  cidr_block = "10.0.1.0/24"
}

module "aws_key_pair" {
  source              = "git::https://github.com/cloudposse/terraform-aws-key-pair.git?ref=tags/0.4.0"
  namespace           = "namespace"
  stage               = "stage"
  name                = "test"
  ssh_public_key_path = "/secrets"
  generate_ssh_key    = true
}

module "ec2_bug" {
  source           = "git::https://github.com/cloudposse/terraform-aws-ec2-instance.git?ref=master"
  name             = "test"
  environment      = "test"
  instance_type    = "t2.micro"
  ami_owner        = data.aws_caller_identity.current.account_id
  instance_profile = aws_iam_instance_profile.test.name
  vpc_id           = data.aws_vpc.default.id
  subnet           = aws_subnet.default.id
  ssh_key_pair     = module.aws_key_pair.key_name
}
```

## Screenshots
n/a

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: MacOS, but using geodesic
 - Terraform v0.12.21

## Additional Context
Feature introduced here: https://github.com/cloudposse/terraform-aws-ec2-instance/pull/60

**Comment by aknysh** [comment]
@ericluria thanks for reporting.
This was addressed in https://github.com/cloudposse/terraform-aws-ec2-instance/pull/73
