### ISSUE TITLE
EBS volumes will be created if enabled = false

### ISSUE THREAD

**Issue by lazzurs** [cloudposse/terraform-aws-ec2-instance#74]
When the variable enabled = false is set the instance is not created but any count of the EBS volumes is.

It is expected from the documentation of enabled that setting this to false will stop creation of the EBS volumes and all resources.

**Comment by Gowiem** [comment]
@lazzurs is this still an issue that you're facing?  If so, mind putting up a patch? Seems like an easy one to fix!

**Comment by lazzurs** [comment]
Let me check later today and if it is I will throw in a patch.
